INSTALL_PATH=$(pwd)
LLVM_INSTALL_PREFIX=$INSTALL_PATH/llvm_install
export PATH=$LLVM_INSTALL_PREFIX/bin:$PATH
export LD_LIBRARY_PATH=$LLVM_INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
export PATH=$LLVM_INSTALL_PREFIX/include:$PATH